### ISSUE TITLE
ptyprocess issue when running on Windows

### ISSUE THREAD

**Issue by rsignell-usgs** [yuvipanda/kubessh#31]
@yuvipanda , @ocefpaf built the [conda-package for kubessh](https://github.com/conda-forge/kubessh-feedstock) and I installed on Windows, but when I run it I get:
```python-traceback
(qhub2) c:\Users\rsignell\Documents\GitHub>kubessh
Traceback (most recent call last):
  File "C:\Users\rsignell\miniconda3\envs\qhub2\Scripts\kubessh-script.py", line 5, in <module>
    from kubessh.app import main
  File "C:\Users\rsignell\miniconda3\envs\qhub2\lib\site-packages\kubessh\app.py", line 15, in <module>
    from kubessh.pod import UserPod, PodState
  File "C:\Users\rsignell\miniconda3\envs\qhub2\lib\site-packages\kubessh\pod.py", line 4, in <module>
    from ptyprocess import PtyProcess
  File "C:\Users\rsignell\miniconda3\envs\qhub2\lib\site-packages\ptyprocess\__init__.py", line 2, in <module>
    from .ptyprocess import PtyProcess, PtyProcessUnicode, PtyProcessError
  File "C:\Users\rsignell\miniconda3\envs\qhub2\lib\site-packages\ptyprocess\ptyprocess.py", line 3, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```
It's clear that the `fcntl` module does not exist on Windows but it seems that depending on what it's used for, there might be [alternatives](
https://github.com/cs01/gdbgui/issues/18#issuecomment-284263708)?

Or is more realistic to say that kubessh will not work on Windows?

**Comment by yuvipanda** [comment]
Hello! Thank you for your interest :) I'm currently focusing on [jupyterhub-ssh](https://github.com/yuvipanda/jupyterhub-ssh) instead, so I've marked this project as inactive. You're welcome to fork and work on this if you wanna, but I'd recommend checking out jupyterhub-ssh for the most common use case :)
